---
# These tasks install http and the php modules.

- name: Install httpd and php
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - apache2
  - php
  - php-mysqlnd

- name: Install web role specific dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - git

- name: Start UFW
  service:
    name: ufw
    state: started
    enabled: yes

- name: insert firewalld rule for httpd
  ufw:
    port: "{{ httpd_port }}/tcp"
    state: enabled
    
- name: apache service state
  service:
    name: apache2
    state: started
    enabled: yes

    #- name: Configure SELinux to allow httpd to connect to remote database
    #  seboolean:
    #    name: httpd_can_network_connect_db
    #    state: true
    #    persistent: yes
